/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import megaSnake.Networker;

import javax.swing.*;
import java.util.Vector;

/**
 *
 * @author obama
 */
public class JoinRoomForm extends javax.swing.JFrame {

    private Networker networker;
    /**
     * Creates new form JoinRoomForm
     */
    public JoinRoomForm(Vector<String> rooms, Networker networker) {
        initComponents();
        this.networker = networker;
        join_room_list.setModel(new AbstractListModel<String>() {
            @Override
            public int getSize() {
                return rooms.size();
            }

            @Override
            public String getElementAt(int index) {
                return rooms.get(index);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        join_room_lable = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        join_room_list = new javax.swing.JList<>();
        join_room_button = new javax.swing.JButton();

        join_room_lable.setText("Rooms");

        join_room_list.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                join_room_listValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(join_room_list);

        join_room_button.setText("Join room");
        join_room_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                join_room_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(join_room_lable)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(join_room_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(join_room_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(join_room_button, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void join_room_listValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_join_room_listValueChanged
        joinRoom();
    }//GEN-LAST:event_join_room_listValueChanged

    private void join_room_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_join_room_buttonActionPerformed
        joinRoom();
    }//GEN-LAST:event_join_room_buttonActionPerformed

    private void joinRoom() {
        String name = join_room_list.getSelectedValue();
        String password = JOptionPane.showInputDialog(this, String.format("Enter password for room %s", name));
        networker.execute("join-room", name, password);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton join_room_button;
    private javax.swing.JLabel join_room_lable;
    private javax.swing.JList<String> join_room_list;
    // End of variables declaration//GEN-END:variables
}
